### ISSUE TITLE
SparkyCI builds fails

### ISSUE THREAD

**Issue by melezhik** [p6-pdf/PDF-Font-Loader-p6#16]
Hi!

Here is the report - http://sparrowhub.io:2222/report/433

21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/cmap-fixed.t ............... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/cmap-utf16.t ............... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/cmap-utf32.t ............... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/cmap-utf8.t ................ ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/cmap-variable.t ............ ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/fontobj.t .................. ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/load-font.t ................ ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/pdf-text-align.t ........... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/reuse-cid.t ................ ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/reuse-type1.t .............. ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/reuse-unembedded.t ......... Dubious, test returned 255
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] All 2 subtests passed 
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/subset.t ................... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/threads.t .................. ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type1-add-encoding.t ....... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type1-encoding.t ........... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type1-encoding_issue#12.t .. ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type1-stream.t ............. ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type1.t .................... ok
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type3-basic.t .............. Dubious, test returned 255
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] All 8 subtests passed 
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] All tests successful.
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] 
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] Test Summary Report
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] -------------------
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/reuse-unembedded.t  (Wstat: 65280 Tests: 0 Failed: 0)
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] Non-zero exit status: 255
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader]   Parse errors: Bad plan.  You planned 2 tests but ran 0.
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] t/type3-basic.t  (Wstat: 65280 Tests: 1 Failed: 0)
21:08:50 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] Non-zero exit status: 255
21:08:51 05/12/2022 [bash: run tests] :: [PDF::Font::Loader]   Parse errors: Bad plan.  You planned 8 tests but ran 1.
21:08:51 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] Files=19, Tests=130,  156 wallclock secs
21:08:51 05/12/2022 [bash: run tests] :: [PDF::Font::Loader] Result: FAILED
21:08:51 05/12/2022 [bash: run tests] :: ===> Testing [FAIL]: PDF::Font::Loader:ver<0.6.2>:auth
21:08:51 05/12/2022 [bash: run tests] :: task exit status: 1

HTH

Aleksei

**Comment by dwarring** [comment]
output from running tests form the shell:
```
alpine@ip-172-31-76-44:~/git/PDF-Font-Loader-raku$ uname -a
Linux ip-172-31-76-44 5.15.5-0-virt #1-Alpine SMP Fri, 26 Nov 2021 11:51:30 +0000 aarch64 Linux
alpine@ip-172-31-76-44:~/git/PDF-Font-Loader-raku$ prove6 -I.
t/cmap-fixed.t ............... ok 
t/cmap-utf16.t ............... ok 
t/cmap-utf32.t ............... ok 
t/cmap-utf8.t ................ ok 
t/cmap-variable.t ............ ok 
t/fontobj.t .................. ok 
t/load-font.t ................ ok   
t/pdf-text-align.t ........... ok 
t/reuse-cid.t ................ ok 
t/reuse-type1.t .............. ok 
Type check failed in assignment to $match; expected FontConfig:D but got FontConfig (FontConfig) (perhaps Nil was assigned to a :D which had no default?)
  in method find-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 92
  in method load-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 52
  in method load-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 64
  in block <unit> at t/reuse-unembedded.t line 14

t/reuse-unembedded.t ......... Dubious, test returned 255
All 2 subtests passed 
t/subset.t ................... ok 
t/threads.t .................. ok 
t/type1-add-encoding.t ....... ok   
t/type1-encoding.t ........... ok 
t/type1-encoding_issue#12.t .. ok 
t/type1-stream.t ............. ok 
t/type1.t .................... ok 
t/type3-basic.t ..............1/8Type check failed in assignment to $match; expected FontConfig:D but got FontConfig (FontConfig) (perhaps Nil was assigned to a :D which had no default?)
  in method find-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 92
  in method load-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 52
  in method load-font at /home/alpine/git/PDF-Font-Loader-raku/lib/PDF/Font/Loader.rakumod (PDF::Font::Loader) line 64
  in block <unit> at t/type3-basic.t line 19

# You planned 8 tests, but ran 1
t/type3-basic.t .............. Dubious, test returned 255
All 8 subtests passed 
All tests successful.

Test Summary Report
-------------------
t/reuse-unembedded.t  (Wstat: 65280 Tests: 0 Failed: 0)
Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/type3-basic.t  (Wstat: 65280 Tests: 1 Failed: 0)
Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 8 tests but ran 1.
Files=19, Tests=130,  190 wallclock secs
Result: FAILED
alpine@ip-172-31-76-44:~/git/PDF-Font-Loader-raku$ 
```

**Comment by melezhik** [comment]
I guess this is the same as on SparkyCI, but with more verbose output …

**Comment by dwarring** [comment]
This module wasn't handling FontConfig failing to find a match. Added FreeMono.ttf as a resource and as a fallback font.

Fixed in latest build http://sparrowhub.io:2222/report/444

**Comment by melezhik** [comment]
Good!
