### ISSUE TITLE
What happens if 'find-font' finds multiple files?

### ISSUE THREAD

**Issue by tbrowder** [p6-pdf/PDF-Font-Loader-p6#27]
From a trial it seems to return the first file found meeting the input criteria. So the docs should say that.

The docs should also clearly state the :find-font option requires Raku module 'FontConfig'.

**Comment by dwarring** [comment]
I think that the `fontconfig` library internally sorts by the selection criteria, then returns the best matching font, so should always returned. It's not filtered fonts just sorting them, so the newly introduced `:all` option will return all known system fonts ordered from best to worst.

Documentation has been edited, and hopefully makes this clearer.

**Comment by tbrowder** [comment]
Thanks, closing as complete.
