### ISSUE TITLE
If possible, for find-font, add named param to select: mono, serif, or sans

### ISSUE THREAD

**Issue by tbrowder** [p6-pdf/PDF-Font-Loader-p6#29]
It looks like one of the fontconfig bin programs (fc-list) shows sans, serif, or mono as "atoms" for fonts it lists. You are not presently using the "style" as a named parameter that I see so far.

**Comment by dwarring** [comment]
Latest PDF::Font::Loader 0.7.1 has a `:serif` option. `:serif` for `:serif` fonts and `:!serif` for sans-serif fonts. This is implemented by passing `serif` or `sans-serif` as the family name to fontconfig, which should treat these as special generic font names. See https://wiki.archlinux.org/title/Font_configuration/Examples#Default_fonts

Also, this release passes any additional `find-font` or `load-font` options through to fontconfig.  A monospace font can be selected by passing `:spacing<mono>`, which is a standard fontconfig property.

**Comment by tbrowder** [comment]
Thanks, David!
