### ISSUE TITLE
Synopsis example should show setting font size

### ISSUE THREAD

**Issue by tbrowder** [p6-pdf/PDF-Font-Loader-p6#37]
The only thing missing is how the font size is set for the SYNOPSIS example.

I think it's done like this:

    :$size

or is it:

    :$font-size

or?

**Comment by dwarring** [comment]
The font-size is set when the font is used. Have amended the synopsis as below:
```raku
use PDF::Font::Loader :&load-font;
my PDF::Content::FontObj $deja = load-font: :file<t/fonts/DejaVuSans.ttf>;
my $font-size = 12;
$pdf.add-page.text: {
    .font = $deja, $font-size;
  .text-position = [10, 600];
  .say: 'Hello, world';
}
```

**Comment by tbrowder** [comment]
Thanks, David. At my age I need that reminder!

You can close this issue if I don't get to it first.
